// PLACE ORDER
export const ORDER_MAKE_REQUEST = "ORDER_MAKE_REQUEST"
export const ORDER_MAKE_SUCCESS = "ORDER_MAKE_SUCCESS"
export const ORDER_MAKE_FAIL = "ORDER_MAKE_FAIL"
export const ORDER_MAKE_RESET = "ORDER_MAKE_RESET"

// ORDER DETAILS
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

// PAYMENT
export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"

// DELIVER ORDER
export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST"
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS"
export const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL"
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET"

// MY ORDER LIST
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST"
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS"
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL"
export const ORDER_LIST_RESET = "ORDER_LIST_RESET"

// ALL ORDER LIST
export const ORDER_ALL_LIST_REQUEST = "ORDER_ALL_LIST_REQUEST"
export const ORDER_ALL_LIST_SUCCESS = "ORDER_ALL_LIST_SUCCESS"
export const ORDER_ALL_LIST_FAIL = "ORDER_ALL_LIST_FAIL"

// DELETE ORDER
export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST'
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS'
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL'